# Taskfile for donate-streaming. Manual deploy from host.
version: "3"

vars:
  UV: uv
  TF_ENV: terraform/environments/prod
  GCP_PROJECT: donatik-486803
  GCP_VM: streaming-worker-vm
  GCP_ZONE: us-central1-a
  GCP_PROXY_PORT: "5432"

tasks:
  default:
    desc: List tasks (task --list).
    cmds:
      - task --list

  deps:install:
    desc: Install Python deps (uv sync).
    cmds:
      - "{{.UV}} sync"

  code:
    desc: Format then lint and typecheck (black, ruff, mypy).
    cmds:
      - "{{.UV}} run black src scripts"
      - "{{.UV}} run ruff check src scripts"
      - "{{.UV}} run black --check src scripts"
      - "{{.UV}} run mypy src"

  test:run:
    desc: Run pytest.
    cmds:
      - "{{.UV}} run pytest"

  app:api:
    desc: Run overlay API locally (port 5099).
    env:
      API__PORT: "5099"
    cmds:
      - "{{.UV}} run overlay-api"

  app:init-db:
    desc: Create DB schema (run once; set DB__* or .env).
    cmds:
      - "{{.UV}} run python scripts/init_db.py"

  tf:plan:
    desc: Terraform init + plan in prod.
    dir: "{{.TF_ENV}}"
    cmds:
      - terraform init -input=false
      - |
        if [ -f terraform.tfvars ]; then
          terraform plan -var-file=terraform.tfvars
        else
          terraform plan -var-file=terraform.tfvars.example
        fi

  tf:output:
    desc: Show Terraform outputs (prod).
    dir: "{{.TF_ENV}}"
    cmds:
      - terraform output

  tf:apply:
    desc: Terraform init + apply in prod (deploy; uses tfvars or example).
    dir: "{{.TF_ENV}}"
    cmds:
      - terraform init -input=false
      - |
        if [ -f terraform.tfvars ]; then
          terraform apply -var-file=terraform.tfvars -auto-approve
        else
          terraform apply -var-file=terraform.tfvars.example -auto-approve
        fi

  gcloud:auth:
    desc: Enable APIs, set project, auth login + application-default login.
    cmds:
      - gcloud services enable compute.googleapis.com sqladmin.googleapis.com iam.googleapis.com youtube.googleapis.com
      - |
        [ -n "{{.GCP_PROJECT}}" ] && gcloud config set project "{{.GCP_PROJECT}}"
        gcloud auth login
        gcloud auth application-default login

  gcloud:ssh:
    desc: SSH into VM.
    cmds:
      - gcloud compute ssh "{{.GCP_VM}}" --zone "{{.GCP_ZONE}}"

  gcloud:scp-docker:
    desc: Copy docker/ to VM.
    cmds:
      - gcloud compute scp --recurse docker "{{.GCP_VM}}:donate-docker" --zone "{{.GCP_ZONE}}"

  gcloud:proxy:
    desc: Run Cloud SQL Auth Proxy via Docker (tf output connection name).
    cmds:
      - |
        CONN="$(cd {{.TF_ENV}} && terraform output -raw cloud_sql_connection_name 2>/dev/null)" || true
        [ -z "$CONN" ] && { echo "Run terraform apply first."; exit 1; }
        docker run --rm -p "{{.GCP_PROXY_PORT}}:5432" gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest "$CONN"

  check:
    desc: Install deps, code, test:run.
    deps:
      - deps:install
      - code
      - test:run
